# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  heidelbergcementwebapi:
    image: heidelbergcementwebapi
    build:
      context: .
      dockerfile: HeidelbergCement.WebApi/Dockerfile
    ports:
      - 5000:5000
